### ISSUE TITLE
Size of a folder is always 4.1 KB

### ISSUE THREAD

**Issue by Alexandre2006** [SatvikR/better-ls#1]
**Operating System:** Linux

**How to reproduce**:

1. Go to any directory containing multiple folders and items (only one folder is needed, but this is to show results clearly)
2. Run better-ls

**Expected result**:

Folders size's are correct

**Result**:

Folders are always 4.1 Kb, no matter there content.
Size is 4096 when human readable mode is not enabled.

**Evidence**:

![Screenshot from 2021-06-04 16-43-21_censored](https://user-images.githubusercontent.com/24361944/120872750-69547700-c554-11eb-83c4-368314b41c72.jpg)

**Comment by SatvikR** [comment]
This is due to the fact that better-ls currently taking the size of the directory object on the file system, which is always 4096 bytes. Fixing this rn.
